namespace Desafio.Domain.Enums;

public enum StatusPedido
{
    APROVADO,
    APROVADO_VALOR_A_MENOR,
    APROVADO_VALOR_A_MAIOR,
    APROVADO_QTD_A_MENOR,
    APROVADO_QTD_A_MAIOR,
    REPROVADO,
    CODIGO_PEDIDO_INVALIDO
}